### ISSUE TITLE
migration problem in postgresql

### ISSUE THREAD

**Issue by Geeknux** [stephenmcd/mezzanine#1262] opened 2015-04-10 16:19 UTC
Hi,
i'm using latest changes on git repo and Django 1.8. while i'm trying to use postgresql after typing:

python manage.py createdb --noinput

i revived this error:

Traceback (most recent call last):
  File "./manage.py", line 34, in <module>
    execute_from_command_line(sys.argv)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Mezzanine-3.1.10-py2.7.egg/mezzanine/core/management/commands/createdb.py", line 60, in handle
    interactive=self.interactive)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/core/management/commands/migrate.py", line 317, in sync_apps
    cursor.execute(statement)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/geeknux/Projects/pgenv/local/lib/python2.7/site-packages/Django-1.8-py2.7.egg/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: relation "django_site" does not exist

i also tried migration for a default django project and it worked without any problem.
something doesn't let mezzanine to create tables in postgres

**Comment by stephenmcd** [comment] 2015-04-10 23:55
Most likely a duplicate of https://github.com/django/django-contrib-comments/issues/30

If I install the git version of that repo, I can create a new DB using the mentioned command with Postgres fine.

**Closed by stephenmcd** 2015-04-10 23:55 UTC
