### ISSUE TITLE
raw_id_fields broken in TabularDynamicInlineAdmin

### ISSUE THREAD

**Issue by slav0nic** [stephenmcd/mezzanine#1376] opened 2015-08-10 14:10 UTC
Popup for lookup function didn't work
Mezzanine 4.0.1

**Comment by stephenmcd** [comment] 2015-08-10 23:33
Dupe of https://github.com/stephenmcd/grappelli-safe/pull/55

**Closed by stephenmcd** 2015-08-10 23:33 UTC
