### ISSUE TITLE
[BUG] "Fixed" URLs are still broken, which can harm your Google ranking.

### ISSUE THREAD

**Issue by Poikilos** [stephenmcd/mezzanine#2034] opened 2022-04-23 12:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing Issues
  - This is related to, but not the same as, issue #2022
  - This is related to, but not the same as, the issue of broken links on <https://pypi.org/project/Mezzanine/> which I reported over e-mail April 10, 2022 since there was no link to this repo there.

### Current Behavior

- The readme was changed to use the github page to replace the domain, but sub-urls such as are still broken.
  - When you click a link in the readme, a GitHub 404 page appears.
  - It looks bad for the project.
  - If the links are erased from the readme, the readme is less useful. Where to find the information from the broken links is unclear. 
- When you click any of several Google results (such as <https://github.com/stephenmcd/mezzanine/docs/packages.html>) about how to use mezzanine, a GitHub 404 page appears.
  - Google tracks this type of thing, so it will harm the ranking of your domain.

### Expected Behavior

- Get the helpful information from the search result of readme somehow.
- Make Google links work to prevent the domain from being downranked.

I didn't know where the official repo was so I mentioned over e-mail that <https://pypi.org/project/Mezzanine/> had bad links. That was fixed since then. However, the following from my e-mail still remains true regarding the "Current Behavior" above:

> . . . https://jupo.org/ [says] ERR_CERT_COMMON_NAME_INVALID.
>
> Do you need hosting? I can probably host this for free on one of my VPSs if you think the site won't be overloaded with traffic, and throw in a domain. I can also help with configuring the domain properly such as using a free cert from https://letsencrypt.org/
> 
> I hope this helps.
> 
> I would like the site back not just so I can use it but also so I can use a tool that has a community of support rather than appearing abandoned. I'm trying to fix the old ninja-ide website and want to make it work with the latest mezzanine. If people don't feel that mezzanine is supported, fewer people will choose it, and therefore fewer people will report issues or submit pull requests. Therefore, even if you provide a URL to me, the site not existing is still a problem.

Plus, I actually want to be able to learn how to do the things to which the readme (used to) link, not just have the links deleted.

### Steps To Reproduce

1. Click any link in the readme or via a search engine that have a "/" after the main site.
2. A 404 error is displayed (and in the case of search results, the error is reported to the search engine for any search engine that uses click tracking such as Google). In the readme, the main site is now the repo, but on Google, the domain redirects to the repo, yielding the same result. *The bad cert on jupo.org may also downrank the domain.*

### Environment

```markdown
- Operating System: N/A
- Python version: N/A
- Django version: N/A
- Database engine and version: N/A
- Mezzanine version: N/A
```

### Anything else?

Examples of search engine results where clicking links on the first page will downrank your domain:
- <https://www.google.com/search?q=mezzanine+5+django&sxsrf=APq-WBu5X0Un-MYsy_EQlBQuYncA5Q0_ng%3A1650717176415&ei=-PFjYvr4GK-vggfH1J2gAw&ved=0ahUKEwj61LLXmKr3AhWvl-AKHUdqBzQQ4dUDCA4&uact=5&oq=mezzanine+5+django&gs_lcp=Cgdnd3Mtd2l6EAMyBQghEKABOgcIABBHELADOgQIIxAnOgYIABAWEB46BQgAEIYDOgUIIRCrAkoECEEYAEoECEYYAFCoHVjyMmC0NGgEcAF4AIABZ4gB_QWSAQM4LjGYAQCgAQHIAQjAAQE&sclient=gws-wiz>
- https://www.bing.com/search?q=mezzanine%205%20documentation&qs=n&form=QBRE&=%25eManage%20Your%20Search%20History%25E&sp=-1&pq=mezzanine%205%20documentation&sc=4-25&sk=&cvid=417941BF500F49FAAB5D3C1E067DD178

Example issue(s) containing links that are now bad, which may lead to issues recurring since people can't find the solution there anymore:
- #1991

Example issue(s) that link to jupo.org which has a bad cert:
- #268
- and every other issue with stephenmcd's signature

Example page(s) that have links to "live demo" that no longer exist (I actually don't know where to find any Mezzanine 5 instance):
- https://github.com/stephenmcd/cartridge

I can't find any documentation on how to set up a mezzanine 5 site other than a page somewhere that said it is now setup the same way as a DJANGO site, which is unclear, because mezzanine isn't DJANGO, so I know steps will differ, but which steps and how? The release's "docs" folder just has rst files which are unformatted and therefore the documents' structure is more difficult to follow visually without a Restructured Text viewer, and I can't click links to other files or have a table of contents even if I get such a viewer.

**Comment by kenbolton** [comment] 2022-04-23 18:08
Seems to me like a duplicate of https://github.com/stephenmcd/mezzanine/issues/2030.

**Comment by poikilos** [comment] 2022-04-23 18:57
> Seems to me like a duplicate of #2030.

That issue covers the readme aspects of my issue description, but not the main issue that is in my issue title. To resolve that, there would either have to be a real website or a set of permanent redirects of individual URLs, which still requires hosting of some sort (even if you just do it [with .htaccess](https://www.semrush.com/blog/301-redirect-htaccess/), [with NGINX](https://www.digitalocean.com/community/tutorials/how-to-create-temporary-and-permanent-redirects-with-nginx), [with Apache](https://www.digitalocean.com/community/tutorials/how-to-create-temporary-and-permanent-redirects-with-apache-and-nginx), etc) unless there is some other way.

**Comment by kenbolton** [comment] 2022-04-23 19:46
The docs now live [here](https://mezzanine.readthedocs.io/en/latest/).

I do not believe that supporting deprecated URLs is possible.

**Comment by poikilos** [comment] 2022-04-23 22:30
Thanks for providing the URL. If there won't be hosting then changing the URLs to point to correct sections at that site would help #2030.

**Comment by poikilos** [comment] 2022-04-24 04:24
Uh, the documentation site still says 4.3.1. Does that imply it is not accurate, or should that be changed?

**Comment by poikilos** [comment] 2022-04-24 04:25
Also, generating a site as per the docs yields a "Home" page that contains the following bad URLs (after converted to markdown for the purposes of this document):

> Welcome to your new Mezzanine powered website. Here are some quick links to get you started:
> - [Log in to the admin interface](http://127.0.0.1:8000/admin/)
> - [Creating custom page types](http://mezzanine.jupo.org/docs/content-architecture.html)
> - [Modifying HTML templates](http://mezzanine.jupo.org/docs/frequently-asked-questions.html#templates)
> - [Changing this homepage](http://mezzanine.jupo.org/docs/frequently-asked-questions.html#why-isn-t-the-homepage-a-page-object-i-can-edit-via-the-admin)
> - [Other frequently asked questions](http://mezzanine.jupo.org/docs/frequently-asked-questions.html)
> - [Full list of settings](http://mezzanine.jupo.org/docs/configuration.html#default-settings)
> - [Deploying to a production server](http://mezzanine.jupo.org/docs/deployment.html)

**Comment by poikilos** [comment] 2022-04-26 11:31
Here's one of possibly dozens or hundreds of tech support answers that are currently faulty due to links to the old site that aren't being redirected:
- https://stackoverflow.com/a/48614890

**Comment by poikilos** [comment] 2022-04-26 11:40
Are you aware you could do this with a "low end box" such as ones listed on [lowendbox.com](https://lowendbox.com/)" VPS for something close to $50/yr in some cases? I'm not affiliated with them, and they just list various vendors so they are not a biased source.

**Comment by kenbolton** [comment] 2022-04-26 15:15
My mistake regarding the domain. Dig that song, though!

Honestly, I feel like this is a solution in search of a problem. Links die, we do what we can to manage it. If the subdomain starts pointing to RTD, cool, but the repo seems like the best place to point it to me.

**Comment by kenbolton** [comment] 2022-04-26 15:44
Please do create pull requests if you feel that you have a solution! I am no authority.

Fixing the links in the [default homepage](https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/core/templates/index.html) of an instance is, to my mind, the only actionable task in this thread. That would be a great first contribution for someone!

The search engines will re-index, and now that the site redirects to github, that shouldn't be a concern. RTD isn't hard to find; the docs in the repository are even easier, though I tend to read those in my editor.

**Comment by kenbolton** [comment] 2024-01-05 16:36
Closing. I can't find any actions we can take to "fix" this, in particular because nothing is, strictly speaking, "broken".

**Closed by kenbolton** 2024-01-05 16:36 UTC
Labels: bug, needs triage

**Comment by Poikilos** [comment] 2024-01-06 22:59
The action to take to fix this is to honor permalinks (on many sites discussing using mezzanine, not just stackoverflow and not just your own docs that you can actually change to point to the new site) that are no longer permanent.
