### ISSUE TITLE
Unable to edit "show in menus"

### ISSUE THREAD

**Issue by keith24** [stephenmcd/mezzanine#1375] opened 2015-08-09 17:32 UTC
Editing pages from the admin interface, I can't make changes to "show in menus" settings.  Other page attributes save as usual.  

![Image of Yaktocat](http://i.imgur.com/FErNf01.gif)

I'm still pretty new to Django/Mezzanine, so don't rule out human error...

**Comment by ryneeverett** [comment] 2015-08-09 23:42
Can't reproduce on master. Might want to take this to [the mailing list](http://groups.google.com/group/mezzanine-users/topics).

**Comment by stephenmcd** [comment] 2015-08-09 23:46
Thanks for verifying Ryne - I'll close this for now.

**Closed by stephenmcd** 2015-08-09 23:46 UTC
