### ISSUE TITLE
mezzanine-comment-* cookies getting populated with wrong user data

### ISSUE THREAD

**Issue by annabunches** [stephenmcd/mezzanine#1560] opened 2016-03-10 17:38 UTC
Users of my site are reporting that sometimes they end up with the comment 'name' and 'email' fields pre-populated with a different user's data. This leaks email addresses.

The cookies in question are mezzanine-comment-name and mezzanine-comment-email. I *have* overridden COMMENT_FORM_CLASS but only to point to this, which I can't imagine is relevant:

    class RecaptchaCommentForm(ThreadedCommentForm):
      def __init__(self, request, *args, **kwargs):
        super(RecaptchaCommentForm, self).__init__(request, *args, **kwargs)
        self.fields['recaptcha'] = RecaptchaField(request)

**Comment by stephenmcd** [comment] 2016-03-10 19:36
I've done a quick review of the code around and don't see anything that could be causing it. That code really hasn't change in over 3 years and I don't suspect it's causing the problem. Other things that could be the cause but probably aren't:

- Shared browsers
- Caching at various layers (is some user's form being cached for others, or some other form of caching via proxy server?)
- JavaScript (is some nefarious script pre-populating the fields)
- You mention in your issue thread possible DB issues around a migration - the comment form can actually be populated by an authenticated user's details, so that's also an avenue

You can probably rule most of these out, but I still don't see this in Mezzanine's code at this stage, so I'll close the issue. Please re-open if you can provide more info.

**Closed by stephenmcd** 2016-03-10 19:36 UTC
