### ISSUE TITLE
Bleach 2.0 compatibility issue

### ISSUE THREAD

**Issue by jlmenut** [stephenmcd/mezzanine#1769] opened 2017-06-09 21:55 UTC
Hello,

I just installed a fresh version of mezzanine (4.2.3) and it seems there is an incompatibility with the bleach version 2.0 which was installed along. I get the error:  

`ImportError: No module named base `

If I downgrade to 1.5 it works fine though

Best regards

**Comment by kenbolton** [comment] 2017-06-09 22:22
This looks like a duplicate of #1741 and #1757. Are you using `mezzanine-pagedown`?

**Comment by jlmenut** [comment] 2017-06-10 21:17
Not that I'm aware I just did a` pip install mezzanine`, and I had no previous install. There is nothing in `pip list `either

**Comment by stephenmcd** [comment] 2017-06-13 00:16
See https://github.com/mozilla/bleach/issues/267

**Closed by stephenmcd** 2017-06-13 00:16 UTC
