### ISSUE TITLE
debug-toolbar break modeltranslation

### ISSUE THREAD

**Issue by slav0nic** [stephenmcd/mezzanine#1358] opened 2015-07-21 17:46 UTC
Django==1.8.3
django-debug-toolbar==1.3.2
django-modeltranslation==0.10
Mezzanine==4.0.0

with 
`OPTIONAL_APPS = (
    "debug_toolbar", ...

i get error:
```pytb
Traceback (most recent call last):
  File "./manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/debug_toolbar/settings.py", line 232, in patch_all
    patch_root_urlconf()
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/debug_toolbar/settings.py", line 220, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/core/urlresolvers.py", line 550, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/core/urlresolvers.py", line 352, in app_dict
    self._populate()
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/core/urlresolvers.py", line 285, in _populate
    for pattern in reversed(self.url_patterns):
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/core/urlresolvers.py", line 402, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/mnt/data2/work/modco-mbm/project/urls.py", line 11, in <module>
    admin.autodiscover()
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/mezzanine/boot/__init__.py", line 77, in autodiscover
    django_autodiscover(*args, **kwargs)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/mezzanine/pages/admin.py", line 245, in <module>
    admin.site.register(Page, PageAdmin)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/mezzanine/boot/lazy_admin.py", line 28, in register
    super(LazyAdminSite, self).register(*args, **kwargs)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 108, in register
    self._registry[model] = admin_class(model, self)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/mezzanine/pages/admin.py", line 55, in __init__
    super(PageAdmin, self).__init__(*args, **kwargs)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/mezzanine/core/admin.py", line 92, in __init__
    super(DisplayableAdmin, self).__init__(*args, **kwargs)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/modeltranslation/admin.py", line 245, in __init__
    super(TranslationAdmin, self).__init__(*args, **kwargs)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/modeltranslation/admin.py", line 33, in __init__
    self.trans_opts = translator.get_options_for_model(self.model)
  File "/home/slav0nic/work/modco-mbm/lib/python3.4/site-packages/modeltranslation/translator.py", line 546, in get_options_for_model
    'translation' % model.__name__)
modeltranslation.translator.NotRegistered: The model "Page" is not registered for translation
```

**Comment by Kniyl** [comment] 2015-07-21 21:34
Does  changing this line: https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/utils/conf.py#L126

into:
```python
prepend("INSTALLED_APPS", app)
```
solves the issue ?

**Comment by stephenmcd** [comment] 2015-07-22 00:41
It's a duplicate of https://github.com/deschler/django-modeltranslation/issues/246

We can solve it in Mezzanine by using the explicit setup for debug toolbar http://django-debug-toolbar.readthedocs.org/en/1.2/installation.html#explicit-setup

I'll push a fix.

**Closed** 2015-07-22 00:43 UTC

**Comment by slav0nic** [comment] 2015-07-22 07:03
yes, this help, tnx
