### ISSUE TITLE
Using AUTH_PROFILE_MODULE - Profile Fields in User Admin Do Not Update

### ISSUE THREAD

**Issue by mmansour** [stephenmcd/mezzanine#1545] opened 2016-02-26 18:47 UTC
To replicate: 

Grab a fresh mezzanine install (Django 1.8 + )

Start an app. 

Create a UserProfile model: e.g. 

```
class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True)
    rate = models.DecimalField(max_digits=8, decimal_places=2)
    social_id = models.CharField(max_length=250, null=True, blank=True)

    def __unicode__(self):
        return self.user.get_full_name()

```
Add 

`AUTH_PROFILE_MODULE = 'myapp.UserProfile' 
`

to settings.py

Go to User admin: Notice in the User admin the new fields to show up. However, add some data and save. The data doesn't not get entered and the fields stay blank.

**Comment by stephenmcd** [comment] 2016-02-26 21:06
Works for me, please try the dev version + dev dependencies. Prob a dupe of #1449

**Closed by stephenmcd** 2016-02-26 21:06 UTC

**Comment by mmansour** [comment] 2016-02-26 21:30
Weird, still not working for me. 

I just created a new virtualenv, grabbed mezz from scratch, started the project, started the app, created the profile as stated above. See the profile fields in the User admin, but when I enter data then hit "Save" the fields stay blank.

**Comment by stephenmcd** [comment] 2016-02-26 21:41
> + dev dependencies

?

**Comment by mmansour** [comment] 2016-02-26 22:01
Oh  not sure! to get dev version I cloned mezz from github. Wouldn't that grab the dev dependencies?

Better new: When I did clone mezz it did fix the that this specific issue. However, now I am dealing with duplicate user profile forms that your link points to. I am getting closer.
