### ISSUE TITLE
RTD not showing new pages

### ISSUE THREAD

**Issue by sjkingo** [stephenmcd/mezzanine#1257] opened 2015-04-08 20:35 UTC
The [build output](https://readthedocs.org/builds/mezzanine/2542689/) on RTD shows that `multi-lingual-sites` is being built as an output page. Yet http://mezzanine.jupo.org/docs/multi-lingual-sites.html is a 404 when it shouldn't be.

Does `/` on RTD point to the latest build, or an old one?

**Comment by stephenmcd** [comment] 2015-04-09 05:16
The docs hosted on the project site aren't on RTD - that's probably why all those RTD regressions went unnoticed, since I don't actually use it. I originally did but as you can imagine from these recent changes, there were a lot of issues arising from not having complete control over the environment, as the case is with the Mezzanine project site's own hosting.

So that link will resolve once the new version is released, and the hosted docs are updated as part of that process, which will be very soon. 

I'm gonna close this for now since it will resolve itself when that happens. Thanks Sam.

**Closed by stephenmcd** 2015-04-09 05:16 UTC

**Comment by sjkingo** [comment] 2015-04-09 05:29
No worries at all. I didn't realise they weren't live docs. Perhaps a note
in the README stating that the docs are also hosted in RTD?
