### ISSUE TITLE
TinyMceWidget HTML source editor fails to load contents of RichTextField in Chrome 43.0.2357.65

### ISSUE THREAD

**Issue by DasAllFolks** [stephenmcd/mezzanine#1303] opened 2015-05-21 23:52 UTC
Mezzanine:  3.1.10
Django:  1.7.8

Whenever I've tried opening up the HTML source editor pop-up for RichTextPages in the Mezzanine admin in Chrome 43.0.2357.65 (64-bit), the HTML editor window has been blank (i.e., having failed to load the contents of the RichTextPage "content" field):

![image](https://cloud.githubusercontent.com/assets/4843949/7761340/8208c36a-ffd9-11e4-8ac2-18345e60c822.png)

Interestingly, I've experienced no such problems with Firefox (37.0.2) or Safari (7.1.6).

**Comment by stephenmcd** [comment] 2015-05-22 16:31
I get the same error.

**Comment by Kniyl** [comment] 2015-05-22 19:09
Tested with chromium, I got the same error. The demo at http://www.tinymce.com/ works fine though.

Maybe that the 3.4.5 version is becoming too old. Can you check if what has been initiated in #705 solves the issue?

**Comment by InvDeath** [comment] 2015-05-24 19:47
My tynymce didn't download after update (master):
http://prntscr.com/78x6m2

**Comment by jerivas** [comment] 2015-05-25 14:35
I've confirmed this issue with a few sites using Mezzanine 3.1.10 and the latest version of Chrome. A report came in that said the issue is present with IE too, but I can't confirm that.

Just FYI, installing tinymezzce4 works flawlessly at least with 3.1.10, so the proposed changes in #705 are probably the fix for this.

**Comment by DasAllFolks** [comment] 2015-05-27 04:01
I can confirm that applying the fix in #705 did indeed fix this problem in Chrome (though I had to mod [tinymce_widget.js](https://github.com/AlexHill/tinymezzce4/blob/master/tinymezzce4/static/tinymezzce4/js/tinymce_setup.js) to get the button for the source code window to show up in the TinyMCE widget in the first place):

```
...
toolbar: ("insertfile undo redo | styleselect | bold italic | " +
                       "alignleft aligncenter alignright alignjustify | " +
                       "bullist numlist outdent indent | link image | code"),
...
```

**Comment by mikeredbike** [comment] 2015-05-27 05:48
Had the same problem with 3.4.5 using  Chrome 43.0.2357.65 (64-bit).  Upgraded to  Chrome 43.0.2357.73 (64-bit) and now it works (no longer blank). IE 11.0.9600.17801 still blank. Chrome 42.0.2311.152 and 43.0.2357.81 are OK.

**Comment by DasAllFolks** [comment] 2015-05-27 06:04
I can confirm, per @mikeredbike's feedback, that upgrading to the latest version of Chrome appears to fix this problem in Chrome.

Previously, I had been on 43.0.2357.65 (64-bit); upgrading to 43.0.2357.81 (64-bit) appears to have fixed this issue.

My impression is that this issue (originally identified strictly for Chrome) might be worth closing out therefore; would someone here be willing to open a separate issue for the problem in IE if we close out this issue?

**Closed** 2015-05-27 06:05 UTC
